# Generated by Django 5.0.2 on 2025-10-13 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_escolar_api', '0004_maestro'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='maestro',
            name='edad',
        ),
        migrations.AddField(
            model_name='maestro',
            name='materias',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
